schema done
hjkmines/hanawilo-project pull request #24
Opened 2022-11-19 01:49 UTC by vmaineng

2022-11-19 02:57 UTC, hjkmines requested changes

2022-11-19 02:57 UTC, hjkmines commented on server/models/Skillset.js
> +    enum: ["Programming Languages", "Frameworks", "Other Technologies"],
@vmaineng  Let's change this to all say without the "s" at the end

2022-11-19 02:57 UTC, hjkmines commented on server/models/Skillset.js
> +    unique: true,
let's change this to `false`

2022-11-19 02:57 UTC, hjkmines commented on server/models/Skillset.js
> +    type: [String],
Let's have this as just `String`

2022-11-19 02:57 UTC, hjkmines commented on server/models/Skillset.js
> +    type: [String],
Let's have this as just `String`

2022-11-19 02:57 UTC, hjkmines commented on server/models/Skillset.js
> +    type: [String],
Let's have this as just `String`

2022-11-19 02:57 UTC, hjkmines commented on server/models/Skillset.js
> +    type: [String],
Let's have this as just `String`

2022-11-19 02:57 UTC, hjkmines commented on server/models/Skillset.js
> +    unique: true,
let's change this to `false`

2022-11-19 02:57 UTC, hjkmines commented on server/models/Skillset.js
> +    unique: true,
let's change this to `false`

2022-11-19 17:38 UTC, hjkmines approved these changes
nice job!

2022-11-19 17:40 UTC, FunkyColdMedyna approved these changes
LGTM !

2022-11-21 18:02 UTC, vinhpeters approved these changes
Looks good! The first programming language I had to learn was MATLAB, glad to see it did not make the cut.

2022-11-21 22:24 UTC, merged