Task 24: Skill set controller
hjkmines/hanawilo-project pull request #25
Opened 2022-11-19 17:25 UTC by JordanJamesTaylor

2022-11-20 16:25 UTC, FunkyColdMedyna approved these changes
LGTM!

2022-11-21 00:31 UTC, hjkmines commented on server/controllers/skillSet.js
> +        const skillSet = await SkillSet.find();
@JordanJamesTaylor let's change this to say `skillSets` since we are getting back more than one.

2022-11-21 00:34 UTC, hjkmines requested changes

2022-11-21 00:34 UTC, hjkmines commented on server/controllers/skillSet.js
> +        .json(skillSet);
change this to `skillSets`

2022-11-21 00:34 UTC, hjkmines commented on server/controllers/skillSet.js
> +        console.log('Error getting skill set');
remove this console log

2022-11-21 00:34 UTC, hjkmines commented on server/controllers/skillSet.js
> +const getSkillSet = async (req, res, next) => {
`getSkillSets`

2022-11-21 00:34 UTC, hjkmines commented on server/controllers/skillSet.js
> +const deleteSkillSet = async (req, res, next) => {
`deleteSkillSets`

2022-11-21 00:34 UTC, hjkmines commented on server/controllers/skillSet.js
> +        const skillSet = await SkillSet.deleteSkillSet();
`skillSets`

2022-11-21 00:34 UTC, hjkmines commented on server/controllers/skillSet.js
> +        .json(response);
`skillSets`

2022-11-21 00:34 UTC, hjkmines commented on server/controllers/skillSet.js
> +        .status(200)
should be `201`

2022-11-21 00:34 UTC, hjkmines commented on server/controllers/skillSet.js
> +        console.log('Error deleting skill sets');
delete this console.log()

2022-11-21 00:34 UTC, hjkmines commented on server/controllers/skillSet.js
> +}
make sure to update this to the correct handler names now that we made them plural :)

2022-11-21 00:34 UTC, hjkmines commented on server/controllers/skillSet.js
> +        console.log('Error creating skill set');
delete the console.log()

2022-11-21 17:51 UTC, hjkmines approved these changes
nice job! LGTM! approved

2022-11-21 18:03 UTC, vinhpeters approved these changes
Nice work!

2022-11-22 14:47 UTC, merged