task25 complete
hjkmines/hanawilo-project pull request #27
Opened 2022-11-23 01:37 UTC by stephsorandom

2022-11-23 06:07 UTC, hjkmines requested changes

2022-11-23 06:07 UTC, hjkmines commented on package-lock.json
> +  "requires": true,
There should not be any changes to the `package-lock.json` file since no new package has been added.

2022-11-23 06:07 UTC, hjkmines commented on server/controllers/getOneSkill.js
> +        const SkillSet = await SkillSet.deleteSkill();
should be  `const SkillSet = await SkillSet.deleteSkill(req.params.skillSetId)`

2022-11-23 06:07 UTC, hjkmines commented on server/controllers/getOneSkill.js
> +        const skillSet = await SkillSet.find();
should be `const skillSet = await SkillSet.find(req.params.skillSetId)`

2022-11-29 00:41 UTC, vmaineng approved these changes
Looks good!

2022-11-29 05:04 UTC, hjkmines approved these changes

2022-12-01 23:44 UTC, vinhpeters approved these changes
LGTM

2022-12-02 00:30 UTC, merged