task1 boiler plate
hjkmines/hanawilo-project pull request #3
Opened 2022-09-22 19:19 UTC by FunkyColdMedyna

Hi Team, 

I made an attempt to set up our boiler plate for the team react app. Please take a look and let me know your thoughts. I initially ran into some problems trying to save time utilizing the command line and "create-react-app"; but this lead to some errors, so i went back through and tried to set everything up manually.

2022-09-22 19:52 UTC, hjkmines requested changes

2022-09-22 19:52 UTC, hjkmines commented on package.json
> +{
@FunkyColdMedyna nice work setting up the boiler plate! 

No need to push up the package-lock.json in the repo, let's add this in our .gitignore

2022-09-22 19:52 UTC, hjkmines commented on .gitignore
> +node_modules
@FunkyColdMedyna nice! Let's add another one here for: package-lock.json

2022-09-22 20:03 UTC, FunkyColdMedyna commented
added package-lock.json to .git_ignore

2022-09-22 20:21 UTC, hjkmines commented
LGTM! @FunkyColdMedyna

2022-09-22 20:21 UTC, hjkmines approved these changes

2022-09-27 18:16 UTC, jordanclrk74 approved these changes

2022-09-27 18:17 UTC, jordanclrk74 approved these changes

2022-09-27 20:46 UTC, merged

2022-09-27 22:56 UTC, mattstead6 reviewed
all good!

2022-09-28 00:55 UTC, JosephThawn commented
Looks good to me!